export const ROOT_PATH = "/"
export const ADMIN_PATH = "/admin"
export const LOG_IN_PATH = "/login"
export const REGISTER_PATH = "/register"
export const MY_TICKET_PATH = "/my-ticket"
export const MOVIE_SHOWING_PATH = "/movies/showing"
export const MOVIE_COMING_PATH = "/movies/coming"
export const MOVIE_DETAIL_PATH = "/movie/:slug"
export const MOVIE_SEARCH_PATH = "/movies/search"
export const EVENT_PATH = "/news"
export const EVENT_DETAIL_PATH = "/news/:slug"
export const USER_PATH = "/users"
export const USER_INFO_PATH = "/users/info"
export const USER_EDIT_PATH = "/users/edit"
export const USER_HISTORY_PATH = "/user/history"

export const default_avatar = "https://i.picsum.photos/id/1005/5760/3840.jpg?hmac=2acSJCOwz9q_dKtDZdSB-OIK1HUcwBeXco_RMMTUgfY"